api:
  build: .
  dockerfile: Dockerfile
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  hostname: api
  stdin_open: true
  container_name: api
  tty: true
  ports:
    - "3000:3000"
  volumes:
    - ${PWD}:/web_service
  env_file:
    - ./docker-env/production.env